[package]
name = "tool_interface"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
serde_json = "1.0"
tokio = { version = "1.45.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }